# Generated by Django 2.2.8 on 2020-03-20 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('disponible', models.BooleanField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsharing.Ciudad')),
                ('idPropietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsharing.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('inicio', models.DateField()),
                ('final', models.DateField()),
                ('idVehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsharing.Vehiculo')),
            ],
        ),
    ]
