# Generated by Django 2.2.8 on 2020-03-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0002_auto_20200322_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='final',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='inicio',
            field=models.DateField(blank=True),
        ),
    ]
