# Generated by Django 2.2.8 on 2020-03-20 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0002_auto_20200320_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
    ]
