# Generated by Django 2.2.8 on 2020-03-20 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0003_remove_usuario_apellido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alquiler',
            options={'verbose_name_plural': 'Alquileres'},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'verbose_name_plural': 'Vehiculos'},
        ),
        migrations.RenameField(
            model_name='alquiler',
            old_name='idVehiculo',
            new_name='vehiculo',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='idPropietario',
            new_name='propietario',
        ),
    ]
