# Generated by Django 3.0.4 on 2020-03-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0005_usuario_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
    ]
