# Generated by Django 2.2.8 on 2020-03-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0006_auto_20200323_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contacto',
            field=models.CharField(max_length=50),
        ),
    ]
