# Generated by Django 3.0.4 on 2020-03-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0007_auto_20200323_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(default='', max_length=50),
        ),
    ]
